# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'TimeLapseWebHost/TimeLapseWebHost.csproj'
    feedsToUse: 'select'
    vstsFeed: '272083fb-59d0-4c3f-9ffb-3355c88311fb'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TimeLapseWebHost/TimeLapseWebHost.csproj'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'TimeLapseWebHost/TimeLapseWebHost.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true